### ISSUE TITLE
FE-Landing Page

### ISSUE THREAD

**Issue by inorimuira** [inorimuira/texas_college_metro#10]
1. Untuk Section Kontak Kami setiap info kontak dilink ke masing-masing tujuannya

- instagram: https://www.instagram.com/texascollege_englishcourse
- map: https://maps.app.goo.gl/xjjQBJi9ZsxCS6nA9
- email: https://mail.google.com/mail/u/0/?tf=cm&fs=1&to=texascollage@gmail.com
- WhatsApp: https://wa.me/+6281373670389

2. Untuk bullet point di section Program Kami jangan pake warna selain hitam, karena bakal dikira link. Jadi diubah ke warna hitam aja.

3. Tambahin effect zoom in (timbul) kalau kursor mengarah ke masing-masing reviewnya di section Review

**Comment by inorimuira** [comment]
<TAMBAHAN> @Henrycarnegie 
1. Poin 3 di atas belum dibuat
2. Button 'Selanjutnya' di page isi-biodata taruh di sebelah kanan bawah
3. Flow step di isi-biodata sama pembayaran taruh di tengah

**Comment by inorimuira** [comment]
![Image](https://github.com/user-attachments/assets/e4679f42-9807-42e9-a37f-4e6f48ff70a9)
untuk button belajar sekarang di hero section sama di gambar yg kedua emang belum ke link ke section pilihprogram ya hen? @Henrycarnegie  ![Image](https://github.com/user-attachments/assets/a43c38e9-6619-48d8-a966-10b9d3b98a8c)

**Comment by Henrycarnegie** [comment]
section "pilih-program" atau page "pilih-program"???

**Comment by inorimuira** [comment]
oiya, page pilih-program

**Comment by inorimuira** [comment]
semuanya ngarah ke page pilih program hen

**Comment by inorimuira** [comment]
![Image](https://github.com/user-attachments/assets/dece4f73-02b9-4d27-bf05-68cc6e9eaf85)

1. Ubah jenis kelas: Kelas Reguler & Kelas Unggulan
2. Button 'Daftar Sekarang' link ke masing-masing page isi biodata&pembayaran sesuai jenis kelas

@Henrycarnegie
