### ISSUE TITLE
FE-feat: Pendaftaran-Siswa

### ISSUE THREAD

**Issue by inorimuira** [inorimuira/texas_college_metro#13]
1. Section Pilih Jenis Program
2. Isi biodata program Program Reguler & Unggulan
3. Upload Bukti Pembayaran

**Comment by inorimuira** [comment]
@Henrycarnegie ![Image](https://github.com/user-attachments/assets/c0fe78ff-6708-44d7-a9b3-f12d9869de49)

1. gaada spasi antara "IsiBiodata" sama "PembayaranKelas" di section isibiodata sama pembayaran
2. better di bagian tanggal lahir input by format date aja ga sih hen?
3. terus kl udah upload bukti pembayaran gaada perubahan di kolom bukti upload pembayaran yg menyatakan kalau file kita udah keupload ya?

**Comment by inorimuira** [comment]
![Image](https://github.com/user-attachments/assets/e18645db-5b5e-4c02-8b2c-ffef87dd8cb5)
1. Di bagian page isi biodata tulisan 'IsiBiobadata" sama "PembayaranKelas" masih belum ada spasi
2. Validasi kolom wajib diisi gaada di page Isi Biodata sama di page Pembayaran. Jadi kalau semua kolom gadiisi (padahal wajib) gaada handler atau notif kalau harus diisi, jadi langsung ke next page.

![Image](https://github.com/user-attachments/assets/064711db-e9ad-4197-b1d4-44960434818d)
1. DI bagian page pembayaran dropdown pilihan pembayaran harusnya: Lunas sama Angsuran
2. Modal atau pop-up reminder&verifikasi setelah klik simpan di page pembayaran belum ada

@Henrycarnegie

**Comment by Henrycarnegie** [comment]
Buat validasi kolom itu dari BE aja, jadi BE yg ngecek fieldnya udh diisi atau belum ya ga @Fadhil-Firoos

**Comment by inorimuira** [comment]
![Image](https://github.com/user-attachments/assets/e6a956f5-5758-4665-98fc-ed842ede6aef)
1. Hover button daftar sekarang belum berubah (masih panjang)

![Image](https://github.com/user-attachments/assets/d8e4e9de-c86a-4734-8b67-4f8536097954)
2. Tambahin kolom pengisian (dropdown) untuk pilih jadwal les

![Image](https://github.com/user-attachments/assets/664ceab4-a838-4c93-af73-1313de658919)
3. Tambahin kolom pengisian untuk jumlah nominal yang dibayar

4. setelah klik simpan, modal verification belum ada


@Henrycarnegie

**Comment by Henrycarnegie** [comment]
buka lagi issuenya klo emng ada revisi @inorimuira
